// This file mirrors the Ponder schema from packages/indexer/ponder.schema.ts
// It provides type safety for @ponder/client queries

export const schema = {
  property: {
    id: "text",
    propertyId: "bigint",
    host: "hex",
    hostSbtTokenId: "bigint",
    ipfsHash: "text",
    propertyType: "text",
    location: "text",
    isActive: "boolean",
    averageRating: "bigint",
    totalRatings: "bigint",
    createdAt: "bigint",
    updatedAt: "bigint",
  },
  roomType: {
    id: "text",
    tokenId: "bigint",
    propertyId: "text",
    roomTypeId: "bigint",
    name: "text",
    ipfsHash: "text",
    pricePerNight: "bigint",
    cleaningFee: "bigint",
    maxGuests: "bigint",
    totalSupply: "bigint",
    isActive: "boolean",
    isDeleted: "boolean",
    createdAt: "bigint",
    updatedAt: "bigint",
  },
  booking: {
    id: "text",
    tokenId: "bigint",
    bookingIndex: "bigint",
    propertyId: "text",
    roomTypeId: "text",
    traveler: "hex",
    checkInDate: "bigint",
    checkOutDate: "bigint",
    totalPrice: "bigint",
    status: "enum", // booking_status enum
    escrowAddress: "hex",
    createdAt: "bigint",
    updatedAt: "bigint",
  },
  user: {
    id: "hex",
    totalPropertiesAsHost: "bigint",
    totalBookingsAsTraveler: "bigint",
    totalReviewsGiven: "bigint",
    totalReviewsReceived: "bigint",
    firstSeenAt: "bigint",
    lastActiveAt: "bigint",
  },
  traveler: {
    id: "text",
    tokenId: "bigint",
    wallet: "hex",
    tier: "enum",
    averageRating: "bigint",
    totalBookings: "bigint",
    completedStays: "bigint",
    cancelledBookings: "bigint",
    totalReviewsReceived: "bigint",
    isSuspended: "boolean",
    memberSince: "bigint",
    lastActivityAt: "bigint",
    updatedAt: "bigint",
  },
  host: {
    id: "text",
    tokenId: "bigint",
    wallet: "hex",
    tier: "enum",
    isSuperHost: "boolean",
    averageRating: "bigint",
    totalPropertiesListed: "bigint",
    totalBookingsReceived: "bigint",
    completedBookings: "bigint",
    totalReviewsReceived: "bigint",
    isSuspended: "boolean",
    memberSince: "bigint",
    lastActivityAt: "bigint",
    updatedAt: "bigint",
  },
} as const;
